### PR TITLE
Python 3 support (issue #5)

### PR DESCRIPTION
**Pull request by monnierj**
I have made, through the use of the Six library, the necessary modifications to support Python 3.4/Python 3.5.

pytest and pytest-html required versions are updated to support Python 3 as well.

The official pytest-circleci repository doesn't support Python 3.x, so I've switched to the fork of pytest-circleci made by @dustinfarris, which supports it.

All non-skipped tests passes for Python 2.7, 3.4 and 3.5. Other versions are untested.

### CODE REVIEW

**Comment by sylvinus** [comment]
Linking to #5

**Comment by sylvinus** [comment]
Thanks a lot @monnierj ! Could you tell us what you think of #18 ? I think I would prefer not adding any dependency but I'm interested in your opinion!

thanks :)

**Comment by monnierj** [comment]
Well, it works the same, but without Six. In that regard, it is better suited to your preferences :)

One missing thing in Liwink's PR is the version bump for Pytest. It worked for him on Python 3.5 because he used Pytest 2.8.7 (which handles the change in the signature of the ast.Call method), I think he just forgot to update the requirements-tests.txt.

And, if you use run **make test** with a Python 3.4/3.5 virtualenv, apart from the errors related to Pytest 2.7, you will encounter an encoding error within pytest-circleci (but as I see issue #16, I suppose that a switch from CircleCI to Travis is planned, so maybe it is not a real issue).

But, apart from this, it works.

**Comment by sylvinus** [comment]
great @monnierj, thanks for the feedbacks! I will bump the pytest version after merging then, and switch to travis indeed to avoid the circle issue you found.

Thanks a lot!

**Pull request closed without merging**
